language: php

php:
  - '7.1'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

notifications:
  email: false
  slack: techinasia:4QrttmVdyMcfBvS42U10pmyX
